In [12]:
# Question 1
def function(array):
    for x in array:
        if x%2!=0:
            print(x)
array = [1,2,3,4,5,6,7,8]
function(array)

1
3
5
7


In [3]:
# Question 2
class Dog():
    def __init__(self,name,breed):
        self.name = name
        self.breed = breed
    
    def bark(self):
        print(f"{self.name} says bow")

dog = Dog("snoopy","bulldog")
dog.bark()

snoopy says bow


In [5]:
# Question 3
import numpy as np
from scipy import stats

x = np.random.randint(0,100 ,(1,100))
print(x)
print(np.median(x))
print(np.mean(x))
print(stats.mode(x[0]))
print(max(x[0])-min(x[0]))
std_dev = 0
for y in x[0]:
    if y > np.mean(x):
        std_dev += y - np.mean(x)
    else: std_dev += np.mean(x) - y
print(std_dev/100)

[[68 64 59 13 16 23 92  3 49 66 41 73 63 84 42 49 76 18 53 92 30 83 47 98
  94 70 41 17 43 26 97 79 91 30 33  4 38 95 59  3 72  2 52 40 30 18 49 18
  86 70 80 41 27 83 51 73 78  5 67 10 27 52 78 59 94 68 86 54 76 28 39 10
  45 76 67 75  4 45 66  4 87 32 66 59 60 71 20 87 25 25 98 51 27  3 17 85
  84 26  0 48]]
51.5
50.98
ModeResult(mode=array([59]), count=array([4]))
98
24.3208


C:\Users\dines\AppData\Local\Temp\ipykernel_18496\304183756.py:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(stats.mode(x[0]))


In [6]:
# Mandatory Question 1
import numpy as np

class prbl():

    def __init__(self):
        self.array = []
    
    def get_array(self):
        length = int(input('Enter the length of Array: '))
        for x in range(length):
            i = int(input('enter value: '))
            self.array.append(i)
        final_array = np.sort(self.array)
        return final_array
        
array1 = prbl()
sorted = array1.get_array()
print(sorted)

Enter the length of Array:  3
enter value:  1
enter value:  9
enter value:  8


[1 8 9]


In [9]:
# Mandatory Question 2
import numpy as np

list = []
for i in range(16):
    x = int(input())
    list.append(x)

arr = np.asarray(list)
arr = arr.reshape(4,4)
print(arr)
Trace = 0 
for i in range(4):
    print(arr[i,i])
    Trace += arr[i,i]
print('trace is',Trace)
for i in range(4):
    print(max(arr[i]))
    print(min(arr[i]))

arr1 = np.linspace(0, 1, num=20, endpoint=True)
arr1 = arr1.reshape(4,5)
print(arr1)

arr3 = arr @ arr1
print(arr3)


 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1
6
11
16
trace is 34
4
1
8
5
12
9
16
13
[[0.         0.05263158 0.10526316 0.15789474 0.21052632]
 [0.26315789 0.31578947 0.36842105 0.42105263 0.47368421]
 [0.52631579 0.57894737 0.63157895 0.68421053 0.73684211]
 [0.78947368 0.84210526 0.89473684 0.94736842 1.        ]]
[[ 5.26315789  5.78947368  6.31578947  6.84210526  7.36842105]
 [11.57894737 12.94736842 14.31578947 15.68421053 17.05263158]
 [17.89473684 20.10526316 22.31578947 24.52631579 26.73684211]
 [24.21052632 27.26315789 30.31578947 33.36842105 36.42105263]]


In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv('Data - STOCK_US_XNYS_CSV.csv')

df['Date'] = pd.to_datetime(df['Date'])


# df = df[cols[0:1] + cols[4:6]]
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['Volume'] = df['Volume'].str.replace(',', '').astype(float)
# print(df.dtypes)

df['total'] = df['Close']*df['Volume']


def result(df): 
    total = df['total'].sum()
    volume = df['Volume'].sum()
    return total / volume
result = df.groupby(['year' , 'month']).apply(result).reset_index(name ='average_closing_value')

print(result)



    year  month  average_closing_value
0   2022      5              39.604632
1   2022      6              38.842517
2   2022      7              39.780205
3   2022      8              37.864697
4   2022      9              33.479498
5   2022     10              29.511188
6   2022     11              24.556332
7   2022     12              26.196142
8   2023      1              30.161266
9   2023      2              33.297415
10  2023      3              31.698324
11  2023      4              28.694983
12  2023      5              27.913987
